development:
  access_key_id: 'AKIAJYKCWTZMXFO2YBNA'
  secret_access_key: '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'
  bucket: 'blognog'

test:
  access_key_id: 'AKIAJYKCWTZMXFO2YBNA'
  secret_access_key: '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'
  bucket: 'blognog'

production:
  access_key_id: 'AKIAJYKCWTZMXFO2YBNA'
  secret_access_key: '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'
  bucket: 'blognog'
